# arch/arm/mach-s3c2450/Makefile
#
# Copyright 2007 Simtec Electronics
#
# Licensed under GPLv2

obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

obj-$(CONFIG_CPU_S3C2450)	+= s3c2450.o
obj-$(CONFIG_CPU_S3C2450)	+= irq.o
obj-$(CONFIG_CPU_S3C2450)	+= clock.o

obj-$(CONFIG_S3C2450_DMA)	+= dma.o
obj-$(CONFIG_S3C2450_PM)	+= pm.o

# Machine support

obj-$(CONFIG_MACH_SMDK2450)	+= mach-smdk2450.o
