#
# Makefile for PWM drivers.
#

obj-$(CONFIG_S3C2443_PWM)       += pwm-s3c2443.o
obj-$(CONFIG_S3C6400_PWM)       += pwm-s3c6400.o
obj-$(CONFIG_S3C2450_PWM)       += pwm-s3c2450.o
obj-$(CONFIG_S3C2416_PWM)       += pwm-s3c2450.o

